name: deploy to deno

on: [push]

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
      - name: Installing project dependencies
      - run: npm install
      - name: Building the project
      - run: npm run build

      - name: clone repository
        uses: actions/checkout@v3

      - name: setup deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      # - name: build site
      #   run: deno task build

      - name: deploy site to deno
        uses: denoland/deployctl@v1
        with:
          project: "peppc"
          import-map: "./deno.json"
          entrypoint: "./main.ts"
